// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAAzGQo56GE0S1i8T36jHGOHe3xP85SZM',
    appId: '1:229676843110:web:997f1e69daa60a8f556da7',
    messagingSenderId: '229676843110',
    projectId: 'ahtasham-ai',
    authDomain: 'ahtasham-ai.firebaseapp.com',
    storageBucket: 'ahtasham-ai.firebasestorage.app',
    measurementId: 'G-0JFBG85Y6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrMHLiRurQAFnDzmOdIgaCvmx-zHIG4zc',
    appId: '1:229676843110:android:2d7332eeeb37d75d556da7',
    messagingSenderId: '229676843110',
    projectId: 'ahtasham-ai',
    storageBucket: 'ahtasham-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzgcHpiBSUg5MOsrb0Dec4mwNe3nKLI-g',
    appId: '1:229676843110:ios:dede1eab3fae4c9c556da7',
    messagingSenderId: '229676843110',
    projectId: 'ahtasham-ai',
    storageBucket: 'ahtasham-ai.firebasestorage.app',
    iosBundleId: 'com.example.ahtashamAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzgcHpiBSUg5MOsrb0Dec4mwNe3nKLI-g',
    appId: '1:229676843110:ios:dede1eab3fae4c9c556da7',
    messagingSenderId: '229676843110',
    projectId: 'ahtasham-ai',
    storageBucket: 'ahtasham-ai.firebasestorage.app',
    iosBundleId: 'com.example.ahtashamAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAAzGQo56GE0S1i8T36jHGOHe3xP85SZM',
    appId: '1:229676843110:web:fb158a92aaa26b4b556da7',
    messagingSenderId: '229676843110',
    projectId: 'ahtasham-ai',
    authDomain: 'ahtasham-ai.firebaseapp.com',
    storageBucket: 'ahtasham-ai.firebasestorage.app',
    measurementId: 'G-3WX03YXZ0Q',
  );
}
